version: "3.9"

services:
  dash-docs:
    restart: "unless-stopped"
    container_name: "dash-docs"
    build:
      context: "dash/"
      dockerfile: "docker/Dockerfile"
    command: "python src/dash_docs.py"
    environment:
      DATA_DIR: "${COMPOSE_PROJECT_NAME}_services"
    volumes:
      - ./dash/src:/app/dash/src
    ports:
      - "8054:8054"
